### ISSUE TITLE
RaspberryPI OS 5.4.83   make install-firmware  => Makefile:10: *** non-numeric first argument to 'word' function: '-1'. Stop

### ISSUE THREAD

**Issue by kuku000** [seemoo-lab/nexmon_csi#361]
I follow the guideline from https://github.com/seemoo-lab/nexmon_csi.
When I come to step 10, I got an error "Makefile:10: *** non-numeric first argument to 'word' function: '-1'. Stop"

(10. Enter the created subdirectory nexmon_csi and run make install-firmware to compile our firmware patch and install it on the Raspberry Pi )

Raspberrypi 3B+
kernel: 5.4.83

**Comment by jlinktu** [comment]
You probably did not setup the build environment by executing `source setup_env.sh` from within the nexmon repositorie's root directory.

**Comment by kuku000** [comment]
I have done it already,
I follow the step:

1. Setup the build environment: source setup_env.sh

2. Run make to extract ucode, templateram and flashpatches from the original firmwares.

3. Navigate to patches/bcm43455c0/7_45_189/ and clone this repository: git clone https://github.com/seemoo-lab/nexmon_csi.git
4. Enter the created subdirectory nexmon_csi and run make install-firmware to compile our firmware patch and install it on the Raspberry Pi.

**Comment by jlinktu** [comment]
The error you are seeing occurs because https://github.com/seemoo-lab/nexmon_csi/blob/fdb25ef0e4e1402e968bb644d4914ad1a3d0a84d/Makefile#L9 produces an empty output. This line splits the content of variable `FW_PATH` based on the delimiter `/`. The variable is read in here: https://github.com/seemoo-lab/nexmon_csi/blob/fdb25ef0e4e1402e968bb644d4914ad1a3d0a84d/Makefile#L2
which in your case should include the following file: [version.mk](https://github.com/seemoo-lab/nexmon/blob/d846e7f48a75695d28167c587ea0b0693577a266/patches/bcm43455c0/7_45_189/version.mk) containing `FW_PATH=$(NEXMON_ROOT)/firmwares/bcm43455c0/7_45_189`.

Check if anything on this way goes wrong for you.

You might have placed `nexmon_csi` in a wrong directory.

**Comment by kuku000** [comment]
got it ,thx!!!
